// <auto-generated />
using System;
using GestionAerolineas.src.shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionAerolineas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420221543_AircraftMigration")]
    partial class AircraftMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionAerolineas.src.Modules.Addresses.Infrastructure.Entity.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("ciudad_id");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("RoadName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_via");

                    b.Property<int>("RoadTypeId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_via_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("RoadTypeId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Aircraft.Infrastructure.Entity.AircraftEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("aerolinea_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activa");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fabricacion");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("matricula");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("ModelId");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.AircraftManufacturers.Infrastructure.Entity.AircraftManufacturerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("aircraftmanufacturers", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.AircraftModels.Infrastructure.Entity.AircraftModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CruiseAltitudeFt")
                        .HasColumnType("int")
                        .HasColumnName("altitud_crucero_ft");

                    b.Property<int?>("CruiseSpeedKmh")
                        .HasColumnType("int")
                        .HasColumnName("velocidad_crucero_kmh");

                    b.Property<decimal?>("FuelConsumptionKgPerHour")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("consumo_combustible_kg_h");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("fabricante_id");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("capacidad_maxima");

                    b.Property<decimal?>("MaxTakeoffWeightKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso_max_despegue_kg");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_modelo");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("aircraftmodels", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Airlines.Infrastructure.Entity.AirlineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("codigo_iata");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("OriginCountryId")
                        .HasColumnType("int")
                        .HasColumnName("pais_origen_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("OriginCountryId");

                    b.ToTable("airlines", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Airports.Infrastructure.Entity.AirportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("ciudad_id");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("codigo_iata");

                    b.Property<string>("IcaoCode")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("codigo_icao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("IataCode")
                        .IsUnique();

                    b.HasIndex("IcaoCode")
                        .IsUnique();

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.AvailabilityStatuses.Infrastructure.Entity.AvailabilityStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("estados_disponibilidad", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.CabinTypes.Infrastructure.Entity.CabinTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CabinTypes", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.CardIssuers.Infrastructure.Entity.CardIssuerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("card_issuers", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.CardTypes.Infrastructure.Entity.CardTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tipos_tarjeta", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.CheckinStatuses.Infrastructure.Entity.CheckinStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("estados_checkin", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Cities.Infrastructure.Entity.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Continents.Infrastructure.Entity.ContinentEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("continents", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Countries.Infrastructure.Entity.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContinentId")
                        .HasColumnType("int")
                        .HasColumnName("continente_id");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("codigo_iso");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.DocumentTypes.Infrastructure.Entity.DocumentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DocumentTypes", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.EmailDomains.Infrastructure.Entity.EmailDomainEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("domain");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("emaildomains", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.FlightRoles.Infrastructure.Entity.FlightRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("fligthroles", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.FlightStates.Infrastructure.Entity.FlightStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("estados_vuelo", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.FlightStatusTransitions.Infrastructure.Entity.FlightStatusTransitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationStateId")
                        .HasColumnType("int")
                        .HasColumnName("estado_destino_id");

                    b.Property<int>("OriginStateId")
                        .HasColumnType("int")
                        .HasColumnName("estado_origen_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinationStateId");

                    b.HasIndex("OriginStateId", "DestinationStateId")
                        .IsUnique();

                    b.ToTable("flightstatustransitions", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.InvoiceItemTypes.Infrastructure.Entity.InvoiceItemTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tipos_item_factura", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.PassengerTypes.Infrastructure.Entity.PassengerTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeMax")
                        .HasColumnType("int")
                        .HasColumnName("edad_max");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("int")
                        .HasColumnName("edad_min");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tipos_pasajero", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.PaymentMethodTypes.Infrastructure.Entity.PaymentMethodTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("payment_method_types", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.PaymentMethods.Infrastructure.Entity.PaymentMethodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardIssuerId")
                        .HasColumnType("int")
                        .HasColumnName("emisor_tarjeta_id");

                    b.Property<int?>("CardTypeId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_tarjeta_id");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_comercial");

                    b.Property<int>("PaymentMethodTypeId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_medio_pago_id");

                    b.HasKey("Id");

                    b.HasIndex("CardIssuerId");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("CommercialName")
                        .IsUnique();

                    b.HasIndex("PaymentMethodTypeId");

                    b.ToTable("paymentmethods", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.PaymentStates.Infrastructure.Entity.PaymentStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("estados_pago", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.People.Infrastructure.Entity.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("direccion_id");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numero_documento");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_documento_id");

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Gender")
                        .HasColumnType("char(1)")
                        .HasColumnName("genero");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DocumentTypeId", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Permissions.Infrastructure.Entity.PermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.PhoneCodes.Infrastructure.Entity.PhoneCodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codigo_pais");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_pais");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .IsUnique();

                    b.ToTable("phonecodes", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Regions.Infrastructure.Entity.RegionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("pais_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.ReservationStatusTransitions.Infrastructure.Entity.ReservationStatusTransitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationStatusId")
                        .HasColumnType("int")
                        .HasColumnName("estado_destino_id");

                    b.Property<int>("OriginStatusId")
                        .HasColumnType("int")
                        .HasColumnName("estado_origen_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinationStatusId");

                    b.HasIndex("OriginStatusId", "DestinationStatusId")
                        .IsUnique();

                    b.ToTable("transiciones_estado_reserva", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.ReservationStatuses.Infrastructure.Entity.ReservationStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("reservationstatus", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.RoadTypes.Infrastructure.Entity.RoadTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RoadTypes", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.RolePermissions.Infrastructure.Entity.RolePermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("rolepermissions", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Seasons.Infrastructure.Entity.SeasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PriceFactor")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("precio_factor");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("temporadas", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.SeatLocationTypes.Infrastructure.Entity.SeatLocationTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tipos_ubicacion_asiento", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.StaffRoles.Infrastructure.Entity.StaffRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("cargos_personal", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.SystemRoles.Infrastructure.Entity.SystemRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles_sistema", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.TicketStatuses.Infrastructure.Entity.TicketStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("estados_tiquete", (string)null);
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Addresses.Infrastructure.Entity.AddressEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Cities.Infrastructure.Entity.CityEntity", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionAerolineas.src.Modules.RoadTypes.Infrastructure.Entity.RoadTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("RoadTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Aircraft.Infrastructure.Entity.AircraftEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Airlines.Infrastructure.Entity.AirlineEntity", null)
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionAerolineas.src.Modules.AircraftModels.Infrastructure.Entity.AircraftModelEntity", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.AircraftManufacturers.Infrastructure.Entity.AircraftManufacturerEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Countries.Infrastructure.Entity.CountryEntity", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.AircraftModels.Infrastructure.Entity.AircraftModelEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.AircraftManufacturers.Infrastructure.Entity.AircraftManufacturerEntity", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Airlines.Infrastructure.Entity.AirlineEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Countries.Infrastructure.Entity.CountryEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginCountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Airports.Infrastructure.Entity.AirportEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Cities.Infrastructure.Entity.CityEntity", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Cities.Infrastructure.Entity.CityEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Regions.Infrastructure.Entity.RegionEntity", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Countries.Infrastructure.Entity.CountryEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Continents.Infrastructure.Entity.ContinentEntity", null)
                        .WithMany()
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.FlightStatusTransitions.Infrastructure.Entity.FlightStatusTransitionEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.FlightStates.Infrastructure.Entity.FlightStateEntity", null)
                        .WithMany()
                        .HasForeignKey("DestinationStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionAerolineas.src.Modules.FlightStates.Infrastructure.Entity.FlightStateEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.PaymentMethods.Infrastructure.Entity.PaymentMethodEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.CardIssuers.Infrastructure.Entity.CardIssuerEntity", null)
                        .WithMany()
                        .HasForeignKey("CardIssuerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionAerolineas.src.Modules.CardTypes.Infrastructure.Entity.CardTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionAerolineas.src.Modules.PaymentMethodTypes.Infrastructure.Entity.PaymentMethodTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.People.Infrastructure.Entity.PersonEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Addresses.Infrastructure.Entity.AddressEntity", null)
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionAerolineas.src.Modules.DocumentTypes.Infrastructure.Entity.DocumentTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.Regions.Infrastructure.Entity.RegionEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Countries.Infrastructure.Entity.CountryEntity", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.ReservationStatusTransitions.Infrastructure.Entity.ReservationStatusTransitionEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.ReservationStatuses.Infrastructure.Entity.ReservationStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("DestinationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionAerolineas.src.Modules.ReservationStatuses.Infrastructure.Entity.ReservationStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionAerolineas.src.Modules.RolePermissions.Infrastructure.Entity.RolePermissionEntity", b =>
                {
                    b.HasOne("GestionAerolineas.src.Modules.Permissions.Infrastructure.Entity.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionAerolineas.src.Modules.SystemRoles.Infrastructure.Entity.SystemRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
